-- `prices` 의 겹치는 인덱스를 지운다 (docs/infra.md 25.22).
--
-- 왜 지우나. **D1 은 쓰기를 셀 때 인덱스까지 센다.** `prices` 한 행을 넣으면
--   표 1 + UNIQUE(stock_id, date) 자동 인덱스 + idx_prices_stock_date + idx_prices_date
-- 가 함께 쓰여 하루 한도(10만 행)를 네 배 빨리 태운다. 2026-09-19·20 실측으로 배수는 정확히 4.00
-- 이었다(거래일 75일 × 873종목 = 65,475 논리행 → 카운터 262,045).
--
-- `idx_prices_stock_date (stock_id, date DESC)` 는 `UNIQUE (stock_id, date)` 가 만드는
-- `sqlite_autoindex_prices_1` 과 **열 구성이 같다.** SQLite 는 인덱스를 거꾸로도 훑으므로
-- DESC 만으로는 별도 인덱스가 필요 없다.
--
-- 실측 (2026-09-20, 873종목 × 250거래일 = 218,250행, 로컬 SQLite. 질의마다 400종목 반복):
--
--   질의                계획        있음(초)  없음(초)
--   종가 최신 1건        같다         0.002    0.002
--   최근 200일          같다         0.052    0.053
--   기간 훑기            같다         0.029    0.028
--   마지막 거래일         같다         0.001    0.001
--   기준일 이전 종가      같다         0.002    0.001
--   20일 평균 거래대금    같다         0.004    0.003
--
-- 실행계획은 인덱스 이름(`idx_prices_stock_date` → `sqlite_autoindex_prices_1`)만 바뀌고
-- 접근 방식(SEARCH · 제약 조건 · COVERING)이 모두 같다. **정렬용 임시 B-TREE 도 생기지 않는다** —
-- 이것이 DESC 를 자동 인덱스가 감당한다는 증거다.
--
-- `idx_prices_date` 는 **남긴다.** 0026 의 근거가 그대로 유효하다 — 날짜만으로 찾는 질의
-- (시장별 최신 시세일, 백필의 "이미 저장된 날")는 이 인덱스가 없으면 종목 수만큼 탐색한다.
--
-- 효과: 한 행당 D1 쓰기 4 → 3. **같은 하루 예산으로 받는 거래일이 33% 는다.**
-- 인덱스를 다시 더하면 `batch/jobs/backfill_kr.py` 의 `PRICE_ROW_D1_COST` 도 함께 올려야 한다.

DROP INDEX IF EXISTS idx_prices_stock_date;
